/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desktop_simple.glb -T 
Files: desktop_simple.glb [14.7MB] > C:\Users\yures\Documents\Intern\React Three Fiber\My Portfolio\public\models\desktop_simple-transformed.glb [1.5MB] (90%)
Author: Nelesh_surve (https://sketchfab.com/Nelesh_surve)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desktop-computer-simple-850e244791574894a9b8c5134468e64a
Title: Desktop_computer_simple
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function YellowDesktop(props) {
  const { nodes, materials } = useGLTF("/models/desktop_simple-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface537_table_wood1_0.geometry}
        material={materials.table_wood1}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface537_table_wood2_0.geometry}
        material={materials.table_wood2}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface504_pen_holder_0.geometry}
        material={materials.pen_holder}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface381_system_cpu_0.geometry}
        material={materials.system_cpu}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mousepCube7_system_mouse_0.geometry}
        material={materials.system_mouse}
        position={[-0.085, 0.049, -0.082]}
        rotation={[0, 1.561, 0]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface377_system_monitor_0.geometry}
        material={materials.system_monitor}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface497_system_keyboard_0.geometry}
        material={materials.system_keyboard}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface503_book_0.geometry}
        material={materials.book}
        position={[0.005, 0.048, -0.055]}
        rotation={[0, 1.297, 0]}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface213_chair_cushion_0.geometry}
        material={materials.chair_cushion}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface213_chair_wood1_0.geometry}
        material={materials.chair_wood1}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/desktop_simple-transformed.glb");
